/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vel_on_time;

/**
 *
 * @author jose noel mantilla
 */
public class cotizacion_finall extends javax.swing.JFrame {

private int gastro2;
private int deco2;
private int serv2;
private int lug2;
private int dia2;
private int mes2;
private int ano2;
private int base_gastro;
private int base_deco;
private int base_serv;
private int base_lug;

 String gastro_fin;
 String deco_fin;
 String serv_fin;
 String lug_fin;
 String dia_fin;
 String mes_fin;
 String ano_fin;
 String base_gastro_fin;
 String base_deco_fin;
 String base_serv_fin;
 String base_lug_fin;


    /**
     * Creates new form cotizacion_final
     */
    public cotizacion_finall() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tit_cot = new javax.swing.JLabel();
        tit_gastro = new javax.swing.JLabel();
        tit_deco = new javax.swing.JLabel();
        tit_serv = new javax.swing.JLabel();
        tit_lug = new javax.swing.JLabel();
        rev_tot_gastro = new javax.swing.JTextField();
        rev_tot_deco = new javax.swing.JTextField();
        rev_tot_serv = new javax.swing.JTextField();
        rev_tot_lug = new javax.swing.JTextField();
        tit_fecha = new javax.swing.JLabel();
        rev_fecha = new javax.swing.JTextField();
        finalizar_cliente = new javax.swing.JButton();
        otra_cot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tit_cot.setText("COTIZACIÓN DEL CLIENTE");

        tit_gastro.setText("GASTRONOMIA TOTAL");

        tit_deco.setText("DECORACIÓN TOTAL");

        tit_serv.setText("SERVICIOS TOTAL");

        tit_lug.setText("LUGAR TOTAL");

        rev_tot_deco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rev_tot_decoActionPerformed(evt);
            }
        });

        tit_fecha.setText("FECHA DEL EVENTO");

        finalizar_cliente.setText("FINALIZAR");

        otra_cot.setText("HACER OTRA COTIZACIÓN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tit_gastro)
                    .addComponent(tit_deco, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tit_serv, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tit_lug, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rev_tot_lug, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(rev_tot_serv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rev_tot_deco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rev_tot_gastro, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rev_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tit_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tit_cot, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(309, 309, 309))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(otra_cot)
                .addGap(71, 71, 71)
                .addComponent(finalizar_cliente)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(tit_cot)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tit_gastro)
                    .addComponent(rev_tot_gastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tit_deco)
                        .addComponent(rev_tot_deco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tit_fecha))
                .addGap(29, 29, 29)
                .addComponent(rev_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tit_serv)
                    .addComponent(rev_tot_serv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tit_lug)
                    .addComponent(rev_tot_lug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalizar_cliente)
                    .addComponent(otra_cot))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rev_tot_decoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rev_tot_decoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rev_tot_decoActionPerformed
    
    public void llegada_final(int prec_gastro, int prec_deco,int prec_serv,int prec_lug,int gastro,int deco,int serv,int lug,int dia,int mes,int ano){
        
         gastro2= gastro;
         deco2=deco;
         serv2=serv;
         lug2=lug;
         dia2=dia;
         mes2=mes;
         ano2=ano;
         
         this.gastro2=gastro2;
         this.deco2=deco2;
         this.serv2=serv2;
         this.lug2=lug2;
         this.dia2=dia2;
         this.mes2=mes2;
         this.ano2=ano2;
         cotizacion();
         
    }
    void cotizacion(){
        
        gastro_fin = Integer.toString(gastro2);
        deco_fin = Integer.toString(deco2);
        serv_fin = Integer.toString(serv2);
        lug_fin = Integer.toString(lug2);
        dia_fin = Integer.toString(dia2);
        mes_fin = Integer.toString(mes2);
        ano_fin = Integer.toString(ano2);
        rev_tot_gastro.setText(gastro_fin);
        rev_tot_deco.setText(deco_fin);
        rev_tot_serv.setText(serv_fin); 
        rev_tot_lug.setText(lug_fin);
        String fecha=dia_fin+"/"+mes_fin+"/"+ano_fin+"/";
        rev_fecha.setText(fecha);
              
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cotizacion_finall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cotizacion_finall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cotizacion_finall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cotizacion_finall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cotizacion_finall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finalizar_cliente;
    private javax.swing.JButton otra_cot;
    private javax.swing.JTextField rev_fecha;
    private javax.swing.JTextField rev_tot_deco;
    private javax.swing.JTextField rev_tot_gastro;
    private javax.swing.JTextField rev_tot_lug;
    private javax.swing.JTextField rev_tot_serv;
    private javax.swing.JLabel tit_cot;
    private javax.swing.JLabel tit_deco;
    private javax.swing.JLabel tit_fecha;
    private javax.swing.JLabel tit_gastro;
    private javax.swing.JLabel tit_lug;
    private javax.swing.JLabel tit_serv;
    // End of variables declaration//GEN-END:variables
}
