
package vel_on_time;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author jose noel mantilla
 */
public class Cotizadoor extends javax.swing.JFrame {
int x;
int y;
int tot;
int tot2;
boolean gastro;
boolean deco;
boolean serv;
boolean lug;
private int id2;
private String name2;
private int pres2;
private int dia2;
private int mes2;
private int ano2;
private int numIn;
int cont =0;
int cont2=0;
int cont4=0;
int cont3=0;
String gast="";
String deocr="";
String servi="";
String lrgs="";
String numI2=" ";
    /**
     * Creates new form Cotizador
     */
    public Cotizadoor() {
        initComponents();
        
        sele_cot.add(gastronomia);
        sele_cot.add(decoracion);
        sele_cot.add(servicios);
        sele_cot.add(lugar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sele_cot = new javax.swing.ButtonGroup();
        DE_TEXT = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        unit_prov = new javax.swing.JTextArea();
        ar_car_1 = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        mutiplicado = new javax.swing.JTextField();
        tit_multi = new javax.swing.JLabel();
        proveedor_cot = new javax.swing.JLabel();
        enviar_cotizar = new javax.swing.JButton();
        lugar = new javax.swing.JRadioButton();
        servicios = new javax.swing.JRadioButton();
        decoracion = new javax.swing.JRadioButton();
        gastronomia = new javax.swing.JRadioButton();
        selc_evento2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        env_final = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combo_gastro = new javax.swing.JComboBox<>();
        combo_deco = new javax.swing.JComboBox<>();
        combo_serv = new javax.swing.JComboBox<>();
        combo_lugar = new javax.swing.JComboBox<>();
        combo_art_gastro = new javax.swing.JComboBox<>();
        combo_art_deco = new javax.swing.JComboBox<>();
        combo_art_serv = new javax.swing.JComboBox<>();
        combo_art_lugar = new javax.swing.JComboBox<>();
        ar_car_2 = new javax.swing.JButton();
        ar_car_3 = new javax.swing.JButton();
        ar_car_4 = new javax.swing.JButton();
        elec_gastro = new javax.swing.JButton();
        elec_deco = new javax.swing.JButton();
        elec_serv = new javax.swing.JButton();
        elec_lugar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        art_unit = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DE_TEXT.setText("PROVEDOR DE:");
        getContentPane().add(DE_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 121, 36));

        unit_prov.setColumns(20);
        unit_prov.setRows(5);
        jScrollPane2.setViewportView(unit_prov);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 430, 219));

        ar_car_1.setText("Agregar al carrito");
        ar_car_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ar_car_1MouseClicked(evt);
            }
        });
        getContentPane().add(ar_car_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 520, -1, -1));

        volver.setText("VOLVER");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 131, 85, -1));

        mutiplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mutiplicadoActionPerformed(evt);
            }
        });
        getContentPane().add(mutiplicado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 900, 170, 30));

        tit_multi.setText("NUMERO DE INVITADOS");
        getContentPane().add(tit_multi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 860, 143, 30));

        proveedor_cot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(proveedor_cot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 273, 50));

        enviar_cotizar.setText("COTIZAR");
        enviar_cotizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviar_cotizarMouseClicked(evt);
            }
        });
        enviar_cotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar_cotizarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar_cotizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 99, -1, -1));

        lugar.setText("LUGAR");
        getContentPane().add(lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 131, -1, -1));

        servicios.setText("SERVICIOS");
        getContentPane().add(servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 131, -1, -1));

        decoracion.setText("DECORACION Y AMBIENTACION");
        decoracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decoracionActionPerformed(evt);
            }
        });
        getContentPane().add(decoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 91, -1, -1));

        gastronomia.setText("GASTRONOMIA");
        getContentPane().add(gastronomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 91, -1, -1));

        selc_evento2.setText("COTIZAR:");
        getContentPane().add(selc_evento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 39, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 194, 1226, 10));

        env_final.setText("Finalizar Cotizacion");
        env_final.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                env_finalMouseClicked(evt);
            }
        });
        getContentPane().add(env_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 900, -1, -1));

        jLabel5.setText("GASTRONOMIA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));

        jLabel6.setText("DECORACIÓN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        jLabel7.setText("SERVICIOS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 700, -1, -1));

        jLabel8.setText("LUGAR");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 790, -1, -1));
        getContentPane().add(combo_gastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 220, -1));
        getContentPane().add(combo_deco, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 220, -1));
        getContentPane().add(combo_serv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 700, 220, -1));
        getContentPane().add(combo_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 790, 220, -1));
        getContentPane().add(combo_art_gastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 220, -1));
        getContentPane().add(combo_art_deco, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, 220, -1));
        getContentPane().add(combo_art_serv, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 700, 220, -1));
        getContentPane().add(combo_art_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 790, 220, -1));

        ar_car_2.setText("Agregar al carrito");
        ar_car_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ar_car_2MouseClicked(evt);
            }
        });
        getContentPane().add(ar_car_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 610, 133, -1));

        ar_car_3.setText("Agregar al carrito");
        ar_car_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ar_car_3MouseClicked(evt);
            }
        });
        getContentPane().add(ar_car_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 700, 133, -1));

        ar_car_4.setText("Agregar al carrito");
        ar_car_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ar_car_4MouseClicked(evt);
            }
        });
        getContentPane().add(ar_car_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 790, 133, -1));

        elec_gastro.setText("Elegir");
        elec_gastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elec_gastroMouseClicked(evt);
            }
        });
        getContentPane().add(elec_gastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, -1, -1));

        elec_deco.setText("Elegir");
        elec_deco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elec_decoMouseClicked(evt);
            }
        });
        elec_deco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elec_decoActionPerformed(evt);
            }
        });
        getContentPane().add(elec_deco, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, -1, -1));

        elec_serv.setText("ELegir");
        elec_serv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elec_servMouseClicked(evt);
            }
        });
        elec_serv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elec_servActionPerformed(evt);
            }
        });
        getContentPane().add(elec_serv, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 700, -1, -1));

        elec_lugar.setText("Elegir");
        elec_lugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elec_lugarMouseClicked(evt);
            }
        });
        getContentPane().add(elec_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 790, -1, -1));

        art_unit.setColumns(20);
        art_unit.setRows(5);
        jScrollPane1.setViewportView(art_unit);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 510, 220));

        jLabel1.setText("ARTICULOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ar_car_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ar_car_1MouseClicked
           
        String gastro_rev_uni = (String) combo_art_gastro.getSelectedItem();
        String id[] = gastro_rev_uni.split(",");
        String p[] = gastro_rev_uni.split(",");
        gast=gast+id[0]+";"+p[1]+";";
        int almax= Integer.parseInt(id[1]);
        cont=cont+almax;
        System.out.println(cont + gast);
        
        
        
        
    }//GEN-LAST:event_ar_car_1MouseClicked

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
       Evento ob21 = new Evento();
       
       ob21.setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_volverMouseClicked
public void llegada(int id,String name,int pres,int numI,int dia,int mes,int ano){
         numIn= numI;
         id2=id;
         name2=name;
         pres2=pres;
         dia2=dia;
         mes2=mes;
         ano2=ano;
         this.id2=id2;
         this.name2=name2;
         this.pres2=pres2;
         this.numIn=numIn;
         this.dia2=dia2;
         this.mes2=mes2;
         this.ano2=ano2;
         
         
    }
    private void enviar_cotizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_cotizarMouseClicked
       
       
      if( gastronomia.isSelected()){
          gastronomia2();
            numI2 = Integer.toString(numIn);
            mutiplicado.setText(numI2);
      }
      if( decoracion.isSelected()){
          decoracion2();
          numI2 = Integer.toString(numIn);
            mutiplicado.setText(numI2);
      }
      if( servicios.isSelected()){
          servicios2();
          numI2 = Integer.toString(numIn);
            mutiplicado.setText(numI2);
      }
      if( lugar.isSelected()){
          lugar2();
          numI2 = Integer.toString(numIn);
          mutiplicado.setText(numI2);
          
      }
      
    }//GEN-LAST:event_enviar_cotizarMouseClicked

    private void env_finalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_env_finalMouseClicked
       
        cotizacion_finall ob28 = new cotizacion_finall();
        ob28.setVisible(true);
        ob28.llegada_final(cont, cont2, cont3, cont4, dia2, mes2, ano2);
        this.setVisible(false);
    }//GEN-LAST:event_env_finalMouseClicked
    
    private void mutiplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mutiplicadoActionPerformed

    }//GEN-LAST:event_mutiplicadoActionPerformed

    private void elec_servActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elec_servActionPerformed
     
    }//GEN-LAST:event_elec_servActionPerformed

    private void elec_gastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elec_gastroMouseClicked
        archivoos ob27 = new archivoos();
        String gastro_rev_uni = (String) combo_gastro.getSelectedItem();
        String id[] = gastro_rev_uni.split(",");
        String nme[] = gastro_rev_uni.split(",");
        String id2 = id[0];
        ob27.archprovar(1,nme[1], id2);
        gastronomia(id2);
    }//GEN-LAST:event_elec_gastroMouseClicked

    private void decoracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decoracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decoracionActionPerformed

    private void enviar_cotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar_cotizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviar_cotizarActionPerformed

    private void elec_decoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elec_decoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elec_decoActionPerformed

    private void elec_decoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elec_decoMouseClicked
        archivoos ob27 = new archivoos();
        String gastro_rev_uni = (String) combo_deco.getSelectedItem();
        String id[] = gastro_rev_uni.split(",");
        String nme[] = gastro_rev_uni.split(",");
        String id2 = id[0];
        ob27.archprovar(2,nme[1], id2);
        decoracion(id2);
        
    }//GEN-LAST:event_elec_decoMouseClicked

    private void elec_servMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elec_servMouseClicked
           archivoos ob27 = new archivoos();
        String gastro_rev_uni = (String) combo_serv.getSelectedItem();
        String id[] = gastro_rev_uni.split(",");
        String nme[] = gastro_rev_uni.split(",");
        String id2 = id[0];
        ob27.archprovar(3,nme[1], id2);
        servicio(id2);
    }//GEN-LAST:event_elec_servMouseClicked

    private void elec_lugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elec_lugarMouseClicked
         archivoos ob27 = new archivoos();
        String gastro_rev_uni = (String) combo_lugar.getSelectedItem();
        String id[] = gastro_rev_uni.split(",");
        String nme[] = gastro_rev_uni.split(",");
        String id2 = id[0];
        ob27.archprovar(4,nme[1], id2);
        lugar(id2);
    }//GEN-LAST:event_elec_lugarMouseClicked

    private void ar_car_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ar_car_2MouseClicked
        String gastro_rev_uni = (String) combo_art_deco.getSelectedItem();
        String id[] = gastro_rev_uni.split(",");
        int almax= Integer.parseInt(id[1]);
        cont2=cont2+almax;
        System.out.println(cont2);
            
    }//GEN-LAST:event_ar_car_2MouseClicked

    private void ar_car_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ar_car_3MouseClicked
        String gastro_rev_uni = (String) combo_art_serv.getSelectedItem();
        String id[] = gastro_rev_uni.split(",");
        int almax= Integer.parseInt(id[1]);
        cont3=cont3+almax;
        System.out.println(cont3);
    }//GEN-LAST:event_ar_car_3MouseClicked

    private void ar_car_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ar_car_4MouseClicked
        String gastro_rev_uni = (String) combo_art_lugar.getSelectedItem();
        String id[] = gastro_rev_uni.split(",");
        int almax= Integer.parseInt(id[1]);
        cont4=cont4+almax;
        System.out.println(cont4);
    }//GEN-LAST:event_ar_car_4MouseClicked

    /**
     * @param args the command line arguments
     */

        
      void gastronomia(String id2){
          
        String a;
       
       
        File archivo = null;  //apuntar al archivo almancenado DD
        FileReader contenido = null;  //acceder a todo el contenido del archivo
        BufferedReader linea = null; //accede linea a linea al contenido

        try {
            archivo = new File("C:\\Users\\jose noel mantilla\\Desktop\\Articulos Comida.txt");
            contenido = new FileReader(archivo);
            linea = new BufferedReader(contenido);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            
            String cadena = ""; //variable captura los datos del archivo
            while ((cadena = linea.readLine()) != null) { //recorre todo el archivo
                int largo = cadena.length();
                String info;
                int prec;
                boolean op;
              String c;
              String id[] = cadena.split(";");
              int id3=Integer.parseInt(id[1]);
                
                String nombre[] = cadena.split(";");
                info = nombre[2];
                String value[] = cadena.split(";");
                prec = Integer.parseInt(value[3]);
                String band[] = cadena.split(";");
                op=Boolean.parseBoolean(band[4]);
               
                if (op==true){
                    if(id2.equals(id[1])){
                        a= "Nombre del articulo: "+info+" Precio: "+prec +"\n";
                      c=info+","+prec;
                      combo_art_gastro.addItem(c); 
                    }
                     
                }
            }

        } catch (IOException e) {
            System.out.print("Error consultando archivo");
        } finally {
            try {
                if (contenido != null) {
                    contenido.close();
                }
            } catch (IOException e1) {
                System.out.print("Error cerrando archivo");
            }
        }
    
      }
    
    
    
    
     void gastronomia2(){
        gastro=true;
        String a;
       
       
        File archivo = null;  //apuntar al archivo almancenado DD
        FileReader contenido = null;  //acceder a todo el contenido del archivo
        BufferedReader linea = null; //accede linea a linea al contenido

        try {
            archivo = new File("C:\\Users\\jose noel mantilla\\Desktop\\Articulos Comida.txt");
            contenido = new FileReader(archivo);
            linea = new BufferedReader(contenido);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            
            String cadena = ""; //variable captura los datos del archivo
            while ((cadena = linea.readLine()) != null) { //recorre todo el archivo
                int largo = cadena.length();
                String info;
                int prec;
                boolean op;
              
              String id[] = cadena.split(";");
              id2=Integer.parseInt(id[1]);
                
                String nombre[] = cadena.split(";");
                info = nombre[2];
                String value[] = cadena.split(";");
                prec = Integer.parseInt(value[3]);
                String band[] = cadena.split(";");
                op=Boolean.parseBoolean(band[4]);
               
                if (op==true){
                      a="id:"+id2+ "Nombre del articulo: "+info+" Precio: "+prec +"\n";
                      art_unit.append(a);
                }
            }

        } catch (IOException e) {
            System.out.print("Error consultando archivo");
        } finally {
            try {
                if (contenido != null) {
                    contenido.close();
                }
            } catch (IOException e1) {
                System.out.print("Error cerrando archivo");
            }
        }
       ////////////////////////////////Leyendo 2 Archivo ////////////////////////////////////////////////
        String b;
        String c;
        File archivo2 = null;  //apuntar al archivo almancenado DD
        FileReader contenido2 = null;  //acceder a todo el contenido del archivo
        BufferedReader linea2 = null; //accede linea a linea al contenido

        try {
           
            archivo2 = new File("C:\\Users\\jose noel mantilla\\Desktop\\Provedores Comida.txt");
            contenido2 = new FileReader(archivo2);
            linea2 = new BufferedReader(contenido2);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            
            String cadena2 = ""; //variable captura los datos del archivo
            while ((cadena2 = linea2.readLine()) != null) { //recorre todo el archivo
                int largo = cadena2.length();
                String serv;
                String name;
                int prec;
                int id2;
                boolean op;
                String id[] = cadena2.split(";");
                id2=Integer.parseInt(id[1]);
                String nombre[] = cadena2.split(";");
                name = nombre[2];
                
                String precb[] = cadena2.split(";");
                prec=Integer.parseInt(precb[3]);
                String value[] = cadena2.split(";");
                serv= value[4];
                String band[] = cadena2.split(";");
                op=Boolean.parseBoolean(band[5]);
                if (op==true){
                    if(serv.equals(" ") && prec==0){
                        b= "Nombre del proveedor: "+ name+"\n";
                         unit_prov.append(b);
                    }else {
                         b= "Nombre del proveedor: " + name+"  Servicios basicos: "+serv+"  Precio: "+prec +"\n";
                      unit_prov.append(b);
                      c=id2+","+name;
                      combo_gastro.addItem(c);
                      
                    }
                     
                }
             
   
            }

        } catch (IOException e) {
            System.out.print("Error consultando archivo" + e);
        } finally {
            try {
                if (contenido2 != null) {
                    contenido2.close();
                }
            } catch (IOException e1) {
                System.out.print("Error cerrando archivo");
            }
        }

        
    }
     void decoracion(String id2){
          
        
        String a;
       
       
        File archivo = null;  //apuntar al archivo almancenado DD
        FileReader contenido = null;  //acceder a todo el contenido del archivo
        BufferedReader linea = null; //accede linea a linea al contenido

        try {
            archivo = new File("C:\\Users\\jose noel mantilla\\Desktop\\Articulos Decoración y ambientación.txt");
            contenido = new FileReader(archivo);
            linea = new BufferedReader(contenido);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            
            String cadena = ""; //variable captura los datos del archivo
            while ((cadena = linea.readLine()) != null) { //recorre todo el archivo
                int largo = cadena.length();
                String info;
                int prec;
                boolean op;
              String c;
              String id[] = cadena.split(";");
              int id3=Integer.parseInt(id[1]);
                
                String nombre[] = cadena.split(";");
                info = nombre[2];
                String value[] = cadena.split(";");
                prec = Integer.parseInt(value[3]);
                String band[] = cadena.split(";");
                op=Boolean.parseBoolean(band[4]);
               
                if (op==true){
                    if(id2.equals(id[1])){
                        a= "Nombre del articulo: "+info+" Precio: "+prec +"\n";
                      c=info+","+prec;
                      combo_art_deco.addItem(c); 
                    }
                     
                }
            }

        } catch (IOException e) {
            System.out.print("Error consultando archivo");
        } finally {
            try {
                if (contenido != null) {
                    contenido.close();
                }
            } catch (IOException e1) {
                System.out.print("Error cerrando archivo");
            }
        }
    
      }
   
    void decoracion2(){
        unit_prov.setText(" ");
         art_unit.setText(" ");
        deco=true;
  
          String a;
        File archivo = null;  //apuntar al archivo almancenado DD
        FileReader contenido = null;  //acceder a todo el contenido del archivo
        BufferedReader linea = null; //accede linea a linea al contenido

        try {
            archivo = new File("C:\\Users\\jose noel mantilla\\Desktop\\Articulos Decoración y ambientación.txt");
            contenido = new FileReader(archivo);
            linea = new BufferedReader(contenido);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            
            String cadena = ""; //variable captura los datos del archivo
            while ((cadena = linea.readLine()) != null) { //recorre todo el archivo
                int largo = cadena.length();
                String info;
                int prec;
                boolean op;
                 
               String id[] = cadena.split(";");
              id2=Integer.parseInt(id[1]);
                
                String nombre[] = cadena.split(";");
                info = nombre[2];
                String value[] = cadena.split(";");
                prec = Integer.parseInt(value[3]);
                String band[] = cadena.split(";");
                op=Boolean.parseBoolean(band[4]);
                if (op==true){
                      a= "Nombre del articulo: "+info+" Precio: "+prec +"\n";
                      art_unit.append(a);
                }
             
   
            }

        } catch (IOException e) {
            System.out.print("Error consultando archivo");
        } finally {
            try {
                if (contenido != null) {
                    contenido.close();
                }
            } catch (IOException e1) {
                System.out.print("Error cerrando archivo");
            }
        }
       ////////////////////////////////Leyendo 2 Archivo ////////////////////////////////////////////////
        String b;
        File archivo2 = null;  //apuntar al archivo almancenado DD
        FileReader contenido2 = null;  //acceder a todo el contenido del archivo
        BufferedReader linea2 = null; //accede linea a linea al contenido

        try {
           
            archivo2 = new File("C:\\Users\\jose noel mantilla\\Desktop\\Provedores Decoración y ambientación.txt");
            contenido2 = new FileReader(archivo2);
            linea2 = new BufferedReader(contenido2);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            
            String cadena2 = ""; //variable captura los datos del archivo
            while ((cadena2 = linea2.readLine()) != null) { //recorre todo el archivo
                int largo = cadena2.length();
                String serv;
                String name;
                String c;
                int prec;
                boolean op;
                
                String nombre[] = cadena2.split(";");
                name = nombre[2];
                
                String precb[] = cadena2.split(";");
                prec=Integer.parseInt(precb[3]);
                String value[] = cadena2.split(";");
                serv= value[4];
                String band[] = cadena2.split(";");
                op=Boolean.parseBoolean(band[5]);
                if (op==true){
                    if(serv.equals(" ") && prec==0){
                        b= "Nombre del proveedor: "+ name+"\n";
                         unit_prov.append(b);
                    }else {
                         b= "Nombre del proveedor: " + name+"  Servicios basicos: "+serv+"  Precio: "+prec +"\n";
                      unit_prov.append(b);
                      c=id2+","+name;
                      combo_deco.addItem(c);
                      
                    }
                     
                }
             
   
            }

        } catch (IOException e) {
            System.out.print("Error consultando archivo" + e);
        } finally {
            try {
                if (contenido2 != null) {
                    contenido2.close();
                }
            } catch (IOException e1) {
                System.out.print("Error cerrando archivo");
            }
        }
       
    }
    void servicio(String id2){
                
        
        String a;
       
       
        File archivo = null;  //apuntar al archivo almancenado DD
        FileReader contenido = null;  //acceder a todo el contenido del archivo
        BufferedReader linea = null; //accede linea a linea al contenido

        try {
            archivo = new File("C:\\Users\\jose noel mantilla\\Desktop\\Articulos servicios.txt");
            contenido = new FileReader(archivo);
            linea = new BufferedReader(contenido);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            
            String cadena = ""; //variable captura los datos del archivo
            while ((cadena = linea.readLine()) != null) { //recorre todo el archivo
                int largo = cadena.length();
                String info;
                int prec;
                boolean op;
              String c;
              String id[] = cadena.split(";");
              int id3=Integer.parseInt(id[1]);
                
                String nombre[] = cadena.split(";");
                info = nombre[2];
                String value[] = cadena.split(";");
                prec = Integer.parseInt(value[3]);
                String band[] = cadena.split(";");
                op=Boolean.parseBoolean(band[4]);
               
                if (op==true){
                    if(id2.equals(id[1])){
                        a= "Nombre del articulo: "+info+" Precio: "+prec +"\n";
                      c=info+","+prec;
                      combo_art_serv.addItem(c); 
                    }
                     
                }
            }

        } catch (IOException e) {
            System.out.print("Error consultando archivo");
        } finally {
            try {
                if (contenido != null) {
                    contenido.close();
                }
            } catch (IOException e1) {
                System.out.print("Error cerrando archivo");
            }
        }
    
    
      }
    
   
    void servicios2(){
        serv=true;
        String a;
        File archivo = null;  //apuntar al archivo almancenado DD
        FileReader contenido = null;  //acceder a todo el contenido del archivo
        BufferedReader linea = null; //accede linea a linea al contenido

        try {
            archivo = new File("C:\\Users\\jose noel mantilla\\Desktop\\Articulos servicios.txt");
            contenido = new FileReader(archivo);
            linea = new BufferedReader(contenido);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            
            String cadena = ""; //variable captura los datos del archivo
            while ((cadena = linea.readLine()) != null) { //recorre todo el archivo
                int largo = cadena.length();
                String info;
                int prec;
                boolean op;
              String id[] = cadena.split(";");
              id2=Integer.parseInt(id[1]);
                
                String nombre[] = cadena.split(";");
                info = nombre[2];
                String value[] = cadena.split(";");
                prec = Integer.parseInt(value[3]);
                String band[] = cadena.split(";");
                op=Boolean.parseBoolean(band[4]);
                if (op==true){
                      a= "Nombre del articulo: "+info+" Precio: "+prec +"\n";
                      art_unit.append(a);
                }
             
   
            }

        } catch (IOException e) {
            System.out.print("Error consultando archivo");
        } finally {
            try {
                if (contenido != null) {
                    contenido.close();
                }
            } catch (IOException e1) {
                System.out.print("Error cerrando archivo");
            }
        }
       ////////////////////////////////Leyendo 2 Archivo ////////////////////////////////////////////////
        String b;
        String c;
        File archivo2 = null;  //apuntar al archivo almancenado DD
        FileReader contenido2 = null;  //acceder a todo el contenido del archivo
        BufferedReader linea2 = null; //accede linea a linea al contenido

        try {
           
            archivo2 = new File("C:\\Users\\jose noel mantilla\\Desktop\\Provedores servicios.txt");
            contenido2 = new FileReader(archivo2);
            linea2 = new BufferedReader(contenido2);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            
            String cadena2 = ""; //variable captura los datos del archivo
            while ((cadena2 = linea2.readLine()) != null) { //recorre todo el archivo
                int largo = cadena2.length();
                String serv;
                String name;
                int prec;
                boolean op;
                
                String nombre[] = cadena2.split(";");
                name = nombre[2];
                
                String precb[] = cadena2.split(";");
                prec=Integer.parseInt(precb[3]);
                String value[] = cadena2.split(";");
                serv= value[4];
                String band[] = cadena2.split(";");
                op=Boolean.parseBoolean(band[5]);
                if (op==true){
                    if(serv.equals(" ") && prec==0){
                        b= "Nombre del proveedor: "+ name+"\n";
                         unit_prov.append(b);
                    }else {
                         b= "Nombre del proveedor: " + name+"  Servicios basicos: "+serv+"  Precio: "+prec +"\n";
                      unit_prov.append(b);
                       c=id2+","+name;
                      combo_serv.addItem(c);
                      
                    }
                     
                }
             
   
            }

        } catch (IOException e) {
            System.out.print("Error consultando archivo" + e);
        } finally {
            try {
                if (contenido2 != null) {
                    contenido2.close();
                }
            } catch (IOException e1) {
                System.out.print("Error cerrando archivo");
            }
        }
    }
    
    void lugar(String id2){
         String a;
       
       
        File archivo = null;  //apuntar al archivo almancenado DD
        FileReader contenido = null;  //acceder a todo el contenido del archivo
        BufferedReader linea = null; //accede linea a linea al contenido

        try {
            archivo = new File("C:\\Users\\jose noel mantilla\\Desktop\\lugar.txt");
            contenido = new FileReader(archivo);
            linea = new BufferedReader(contenido);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            
            String cadena = ""; //variable captura los datos del archivo
            while ((cadena = linea.readLine()) != null) { //recorre todo el archivo
                int largo = cadena.length();
                String info;
                int prec;
                boolean op;
              String c;
              String id[] = cadena.split(";");
              int id3=Integer.parseInt(id[1]);
                
                String nombre[] = cadena.split(";");
                info = nombre[2];
                String value[] = cadena.split(";");
                prec = Integer.parseInt(value[3]);
                String band[] = cadena.split(";");
                op=Boolean.parseBoolean(band[4]);
               
                if (op==true){
                    if(id2.equals(id[1])){
                        a= "Nombre del articulo: "+info+" Precio: "+prec +"\n";
                      c=info+","+prec;
                      combo_art_lugar.addItem(c); 
                    }
                     
                }
            }

        } catch (IOException e) {
            System.out.print("Error consultando archivo");
        } finally {
            try {
                if (contenido != null) {
                    contenido.close();
                }
            } catch (IOException e1) {
                System.out.print("Error cerrando archivo");
            }
        }
    }
    
    void lugar2(){
        
        lug=true;
        String a;
        File archivo = null;  //apuntar al archivo almancenado DD
        FileReader contenido = null;  //acceder a todo el contenido del archivo
        BufferedReader linea = null; //accede linea a linea al contenido

        try {
            archivo = new File("C:\\Users\\jose noel mantilla\\Desktop\\lugar.txt");
            contenido = new FileReader(archivo);
            linea = new BufferedReader(contenido);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            
            String cadena = ""; //variable captura los datos del archivo
            while ((cadena = linea.readLine()) != null) { //recorre todo el archivo
                int largo = cadena.length();
                String info;
                int prec;
                boolean op;
               String id[] = cadena.split(";");
              id2=Integer.parseInt(id[1]);
                
                String nombre[] = cadena.split(";");
                info = nombre[2];
                String value[] = cadena.split(";");
                prec = Integer.parseInt(value[3]);
                String band[] = cadena.split(";");
                op=Boolean.parseBoolean(band[4]);
                if (op==true){
                      a= "Nombre del articulo: "+info+" Precio: "+prec +"\n";
                      art_unit.append(a);
                }
             
   
            }

        } catch (IOException e) {
            System.out.print("Error consultando archivo");
        } finally {
            try {
                if (contenido != null) {
                    contenido.close();
                }
            } catch (IOException e1) {
                System.out.print("Error cerrando archivo");
            }
        }
       ////////////////////////////////Leyendo 2 Archivo ////////////////////////////////////////////////
        String b;
        File archivo2 = null;  //apuntar al archivo almancenado DD
        FileReader contenido2 = null;  //acceder a todo el contenido del archivo
        BufferedReader linea2 = null; //accede linea a linea al contenido

        try {
           
            archivo2 = new File("C:\\Users\\jose noel mantilla\\Desktop\\Provedores lugar.txt");
            contenido2 = new FileReader(archivo2);
            linea2 = new BufferedReader(contenido2);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            
            String cadena2 = ""; //variable captura los datos del archivo
            while ((cadena2 = linea2.readLine()) != null) { //recorre todo el archivo
                int largo = cadena2.length();
                String serv;
                String name;
                int prec;
                boolean op;
                String c;
                String nombre[] = cadena2.split(";");
                name = nombre[2];
                
                String precb[] = cadena2.split(";");
                prec=Integer.parseInt(precb[3]);
                String value[] = cadena2.split(";");
                serv= value[4];
                String band[] = cadena2.split(";");
                op=Boolean.parseBoolean(band[5]);
                if (op==true){
                    if(serv.equals(" ") && prec==0){
                        b= "Nombre del proveedor: "+ name+"\n";
                         unit_prov.append(b);
                    }else {
                         b= "Nombre del proveedor: " + name+"  Servicios basicos: "+serv+"  Precio: "+prec +"\n";
                      unit_prov.append(b);
                      c=id2+","+name;
                      combo_lugar.addItem(c);
                    }
                     
                }
             
   
            }

        } catch (IOException e) {
            System.out.print("Error consultando archivo" + e);
        } finally {
            try {
                if (contenido2 != null) {
                    contenido2.close();
                }
            } catch (IOException e1) {
                System.out.print("Error cerrando archivo");
            }
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cotizadoor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cotizadoor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cotizadoor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cotizadoor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cotizadoor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DE_TEXT;
    private javax.swing.JButton ar_car_1;
    private javax.swing.JButton ar_car_2;
    private javax.swing.JButton ar_car_3;
    private javax.swing.JButton ar_car_4;
    private javax.swing.JTextArea art_unit;
    private javax.swing.JComboBox<String> combo_art_deco;
    private javax.swing.JComboBox<String> combo_art_gastro;
    private javax.swing.JComboBox<String> combo_art_lugar;
    private javax.swing.JComboBox<String> combo_art_serv;
    private javax.swing.JComboBox<String> combo_deco;
    private javax.swing.JComboBox<String> combo_gastro;
    private javax.swing.JComboBox<String> combo_lugar;
    private javax.swing.JComboBox<String> combo_serv;
    private javax.swing.JRadioButton decoracion;
    private javax.swing.JButton elec_deco;
    private javax.swing.JButton elec_gastro;
    private javax.swing.JButton elec_lugar;
    private javax.swing.JButton elec_serv;
    private javax.swing.JButton env_final;
    private javax.swing.JButton enviar_cotizar;
    private javax.swing.JRadioButton gastronomia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton lugar;
    private javax.swing.JTextField mutiplicado;
    private javax.swing.JLabel proveedor_cot;
    private javax.swing.JLabel selc_evento2;
    private javax.swing.ButtonGroup sele_cot;
    private javax.swing.JRadioButton servicios;
    private javax.swing.JLabel tit_multi;
    private javax.swing.JTextArea unit_prov;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
