/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vel_on_time;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author jose noel mantilla
 */
public class Evento extends javax.swing.JFrame {

    /**
     * Creates new form Evento
     */
    public Evento() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elec_cotizar = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        evento = new javax.swing.JLabel();
        selc_evento1 = new javax.swing.JLabel();
        nombre_cliente = new javax.swing.JLabel();
        MES = new javax.swing.JLabel();
        numero_invitados = new javax.swing.JLabel();
        id_cliente = new javax.swing.JLabel();
        rev_id = new javax.swing.JTextField();
        rev_nombre = new javax.swing.JTextField();
        rev_presupuesto = new javax.swing.JTextField();
        rev_invitados = new javax.swing.JTextField();
        enviar_cliente = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        presupuesto1 = new javax.swing.JLabel();
        ANO = new javax.swing.JLabel();
        DIA = new javax.swing.JLabel();
        rev_dia = new javax.swing.JTextField();
        rev_mes = new javax.swing.JTextField();
        rev_ano = new javax.swing.JTextField();
        VOLVER = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        horaInicio = new javax.swing.JTextField();
        horafinal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        evento.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        getContentPane().add(evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 276, 50));

        selc_evento1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        selc_evento1.setText("Tipo de evento seleccionado:");
        getContentPane().add(selc_evento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 50));

        nombre_cliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        nombre_cliente.setText("Nombre cliente:");
        getContentPane().add(nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 119, 34));

        MES.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        MES.setText("MES:");
        getContentPane().add(MES, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, 34));

        numero_invitados.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        numero_invitados.setText("Numero de invitados:");
        getContentPane().add(numero_invitados, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 129, 34));

        id_cliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        id_cliente.setText("Id del cliente:");
        getContentPane().add(id_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 85, 34));

        rev_id.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        rev_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rev_idActionPerformed(evt);
            }
        });
        rev_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rev_idKeyTyped(evt);
            }
        });
        getContentPane().add(rev_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 103, -1));

        rev_nombre.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        rev_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rev_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(rev_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 160, -1));

        rev_presupuesto.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        rev_presupuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rev_presupuestoKeyTyped(evt);
            }
        });
        getContentPane().add(rev_presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 103, -1));

        rev_invitados.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        rev_invitados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rev_invitadosKeyTyped(evt);
            }
        });
        getContentPane().add(rev_invitados, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 130, -1));

        enviar_cliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        enviar_cliente.setText("Aceptar");
        enviar_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviar_clienteMouseClicked(evt);
            }
        });
        getContentPane().add(enviar_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 100, 40));

        RESET.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        RESET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trash_full_recycle_delete_delete_9751.png"))); // NOI18N
        RESET.setText("Reset");
        RESET.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RESET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RESETMouseClicked(evt);
            }
        });
        getContentPane().add(RESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 110, 40));

        presupuesto1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        presupuesto1.setText("Presupuesto:");
        getContentPane().add(presupuesto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 85, 34));

        ANO.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        ANO.setText("AÑO:");
        getContentPane().add(ANO, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 39, 34));

        DIA.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        DIA.setText("DIA:");
        getContentPane().add(DIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 36, 34));

        rev_dia.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        rev_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rev_diaActionPerformed(evt);
            }
        });
        rev_dia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rev_diaKeyTyped(evt);
            }
        });
        getContentPane().add(rev_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 60, -1));

        rev_mes.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        rev_mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rev_mesKeyTyped(evt);
            }
        });
        getContentPane().add(rev_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 61, -1));

        rev_ano.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        rev_ano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rev_anoKeyTyped(evt);
            }
        });
        getContentPane().add(rev_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 68, -1));

        VOLVER.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        VOLVER.setText("Volver");
        VOLVER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VOLVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLVERMouseClicked(evt);
            }
        });
        getContentPane().add(VOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 70, 40));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel2.setText("Hora de inicio   Hora de fin");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 160, -1));

        horaInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                horaInicioKeyTyped(evt);
            }
        });
        getContentPane().add(horaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 50, -1));

        horafinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                horafinalKeyTyped(evt);
            }
        });
        getContentPane().add(horafinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marble-2398946_960_720.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rev_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rev_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rev_idActionPerformed

    private void enviar_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_clienteMouseClicked
       
        archivoos ob4= new archivoos();
       int id;
       String name;
       int pres;
       int numI;
       int dia;
       int mes;
       int ano;
       int horai,horaf;
       
      if( (rev_id.getText().length()==0)|| (rev_nombre.getText().length()==0) || (rev_presupuesto.getText().length()==0) || (rev_invitados.getText().length()==0)||(rev_dia.getText().length()==0)||(rev_mes.getText().length()==0)||(rev_ano.getText().length()==0)||(horaInicio.getText().length()==0)||(horafinal.getText().length()==0)){
          //
          JOptionPane.showMessageDialog(null, "Caja de texto vacia"); 
      }
      else{
          
          
       
       id= Integer.parseInt(rev_id.getText());
       name= rev_nombre.getText();
       pres= Integer.parseInt(rev_presupuesto.getText());
       numI= Integer.parseInt(rev_invitados.getText());
       dia= Integer.parseInt(rev_dia.getText());
       mes= Integer.parseInt(rev_mes.getText());
       ano= Integer.parseInt(rev_ano.getText());
       String fecha;
      
       horai=Integer.parseInt(horaInicio.getText());
       horaf=Integer.parseInt(horafinal.getText());
      String tip_evento=(evento.getText());
       
     
      
      
       if(ano<2019|| ano>3000 ){
            JOptionPane.showMessageDialog(null, "No es valido");
       }
       else{
           if(mes>13 || mes<=0){
              JOptionPane.showMessageDialog(null, "No es valido"); 
           }else{
        
            if((mes==1 && dia>31 ||dia<=0) || (mes==2 && dia>28||dia<=0) || (mes==3 && dia>31||dia<=0)||(mes==4 && dia>30||dia<=0)||(mes==5 && dia>31||dia<=0)||(mes==6 && dia>30||dia<=0)||(mes==7 && dia>31||dia<=0)||(mes==8 && dia>31||dia<=0)||(mes==9 && dia>30||dia<=0)||(mes==10 && dia>31||dia<=0)||(mes==11 && dia>30||dia<=0)||(mes==12 && dia>31||dia<=0) ){
                JOptionPane.showMessageDialog(null, "No es valido");
            }
            else{
                if(horai>24 || horaf>24 ||horai<=0 ||horaf<=0 ){
                   JOptionPane.showMessageDialog(null, "No es valido");
                }else{
                  
                    if(dia==31 && mes==12){
                       JOptionPane.showMessageDialog(null, "Este dia no trabajamos"); 
                    }
                    else{
                        if(pres<=0){
                          JOptionPane.showMessageDialog(null, "Presupuesto invalido");   
                        }
                        else{
                            if(numI<=0){
                                JOptionPane.showMessageDialog(null, "Invitados invalidos");  
                            }
                            else{
                                fecha = dia+"/"+mes+"/"+ano;
                                String fechaenh="/"+horai+"/"+horaf;
                                ob4.archCli(id,name,pres,numI,fecha+fechaenh,tip_evento);
                                Cotizadooor ob29= new Cotizadooor();
                                ob29.llegada(id,name,pres,numI,dia,mes,ano,horai,horaf,tip_evento);
                                ob29.setVisible(true);
                                this.setVisible(false);   
                            }
                          
                        }
                        
                       
                    }
                   
                }
            }
           }
       }
       
      }  
    }//GEN-LAST:event_enviar_clienteMouseClicked

    private void RESETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RESETMouseClicked
       rev_id.setText("");
       rev_nombre.setText("");
       rev_presupuesto.setText("");
       rev_invitados.setText("");
    }//GEN-LAST:event_RESETMouseClicked

    private void VOLVERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLVERMouseClicked
       Selec_evento ob26 = new Selec_evento();
       ob26.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_VOLVERMouseClicked

    private void rev_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rev_idKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'|| c>'9')evt.consume();
    }//GEN-LAST:event_rev_idKeyTyped

    private void rev_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rev_nombreKeyTyped
         char c=evt.getKeyChar();
        if(c<'a'|| c>'z')evt.consume();
    }//GEN-LAST:event_rev_nombreKeyTyped

    private void rev_presupuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rev_presupuestoKeyTyped
         char c=evt.getKeyChar();
        if(c<'0'|| c>'9')evt.consume();
    }//GEN-LAST:event_rev_presupuestoKeyTyped

    private void rev_invitadosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rev_invitadosKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'|| c>'9')evt.consume();
    }//GEN-LAST:event_rev_invitadosKeyTyped

    private void rev_diaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rev_diaKeyTyped
         char c=evt.getKeyChar();
        if(c<'0'|| c>'9')evt.consume();
    }//GEN-LAST:event_rev_diaKeyTyped

    private void rev_mesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rev_mesKeyTyped
       char c=evt.getKeyChar();
        if(c<'0'|| c>'9')evt.consume();
    }//GEN-LAST:event_rev_mesKeyTyped

    private void rev_anoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rev_anoKeyTyped
         char c=evt.getKeyChar();
        if(c<'0'|| c>'9')evt.consume();
    }//GEN-LAST:event_rev_anoKeyTyped

    private void horaInicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horaInicioKeyTyped
         char c=evt.getKeyChar();
        if(c<'0'|| c>'9')evt.consume();
    }//GEN-LAST:event_horaInicioKeyTyped

    private void horafinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horafinalKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'|| c>'9')evt.consume();
    }//GEN-LAST:event_horafinalKeyTyped

    private void rev_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rev_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rev_diaActionPerformed

    void quince(){
        evento.setText("15 años");
    }
    void aniversario(){
        evento.setText("Aniversario");
    }
    void matrimonio(){
        evento.setText("Matrimonio");
    }
    void soltero(){
        evento.setText("Despedida de soltero");
    }
    void inaguracion(){
        evento.setText("Inaguración");
    }
    void confirmacion(){
        evento.setText("Confirmación");
    }
    void comunion(){
        evento.setText("Comunion");
    }
    void bautizo(){
        evento.setText("Bautizo");
    }
    void galas(){
        evento.setText("Galas-Cocteles");
    }
    void reuniones(){
        evento.setText("Reuniones de trabajo");
    }
    void cumple(){
        evento.setText("Cumpleaños");
    }
    void cenas(){
        evento.setText("Cenas intimas");
    }
    void reuFam(){
        evento.setText("Reunion Familiar");
    }
    void graduacion(){
        evento.setText("Graducaciones");
    }
    void convenciones(){
        evento.setText("Convenciones y ferias");
    } 
    void baby(){
        evento.setText("Baby Shower");
    }
    void benei(){
        evento.setText("Benei Mitzvá");
    }
    void halloween(){
        evento.setText("Fiesta halloween");
    }
    void sabbat(){
        evento.setText("Sabbat");
    }
    void navidad(){
        evento.setText("Fiesta navideña");
    }
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ANO;
    private javax.swing.JLabel DIA;
    private javax.swing.JLabel MES;
    private javax.swing.JButton RESET;
    private javax.swing.JButton VOLVER;
    private javax.swing.ButtonGroup elec_cotizar;
    private javax.swing.JButton enviar_cliente;
    private javax.swing.JLabel evento;
    private javax.swing.JTextField horaInicio;
    private javax.swing.JTextField horafinal;
    private javax.swing.JLabel id_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nombre_cliente;
    private javax.swing.JLabel numero_invitados;
    private javax.swing.JLabel presupuesto1;
    private javax.swing.JTextField rev_ano;
    private javax.swing.JTextField rev_dia;
    private javax.swing.JTextField rev_id;
    private javax.swing.JTextField rev_invitados;
    private javax.swing.JTextField rev_mes;
    private javax.swing.JTextField rev_nombre;
    private javax.swing.JTextField rev_presupuesto;
    private javax.swing.JLabel selc_evento1;
    // End of variables declaration//GEN-END:variables
}
