/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vel_on_time;

/**
 *
 * @author jose noel mantilla
 */
public class Mod_selec extends javax.swing.JFrame {

    /**
     * Creates new form Mod_evento
     */
    public Mod_selec() {
        initComponents();
        transparenciaBotones();
        mod_prov.add(selec_gastronomia);
        mod_prov.add(selec_decoracion);
        mod_prov.add(selec_servicio);
        mod_prov.add(selec_lugar);
        mod_prov.add(selec_cliente);
        mod_prov.add(selec_art);
        this.setLocationRelativeTo(null);
    }
  String op;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mod_prov = new javax.swing.ButtonGroup();
        MODIFI = new javax.swing.JLabel();
        VOLVER = new javax.swing.JButton();
        deseo = new javax.swing.JLabel();
        selec_gastronomia = new javax.swing.JRadioButton();
        selec_decoracion = new javax.swing.JRadioButton();
        selec_servicio = new javax.swing.JRadioButton();
        selec_lugar = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        TIT_USU = new javax.swing.JLabel();
        selec_cliente = new javax.swing.JRadioButton();
        modificar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        TIT_USU1 = new javax.swing.JLabel();
        selec_art = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MODIFI.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        MODIFI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MODIFI.setText("BIENVENIDO A MODIFICAR");
        MODIFI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(MODIFI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 540, 60));

        VOLVER.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        VOLVER.setText("Volver");
        VOLVER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VOLVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLVERMouseClicked(evt);
            }
        });
        getContentPane().add(VOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 70, 30));

        deseo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        deseo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deseo.setText("¿Que proveedor desea modificar?");
        getContentPane().add(deseo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 540, 30));

        selec_gastronomia.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        selec_gastronomia.setText("Gastronomia");
        selec_gastronomia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selec_gastronomia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/32395greensalad_98843.png"))); // NOI18N
        getContentPane().add(selec_gastronomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 200, -1));

        selec_decoracion.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        selec_decoracion.setText("Decoración");
        selec_decoracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selec_decoracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4_balloon_decoration_christmas_xmas_celebration_party_icon-icons.com_77039.png"))); // NOI18N
        getContentPane().add(selec_decoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 200, -1));

        selec_servicio.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        selec_servicio.setText("Servicio");
        selec_servicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selec_servicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shopping_22120.png"))); // NOI18N
        getContentPane().add(selec_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 150, -1));

        selec_lugar.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        selec_lugar.setText("Lugar");
        selec_lugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selec_lugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/location_map_directions_geography_gps_icon-icons.com_55988.png"))); // NOI18N
        selec_lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selec_lugarActionPerformed(evt);
            }
        });
        getContentPane().add(selec_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 150, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 261, 534, 10));

        TIT_USU.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        TIT_USU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TIT_USU.setText("¿Desea modificar los articulos?");
        getContentPane().add(TIT_USU, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 530, 30));

        selec_cliente.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        selec_cliente.setText("Cliente");
        selec_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selec_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/businessapplication_edit_male_user_thepencil_theclient_negocio_2321.png"))); // NOI18N
        getContentPane().add(selec_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 130, -1));

        modificar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        modificar.setText("Modificar");
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 110, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 402, 530, 10));

        TIT_USU1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        TIT_USU1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TIT_USU1.setText("¿Desea modificar el cliente?");
        getContentPane().add(TIT_USU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 530, 30));

        selec_art.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        selec_art.setText("Articulos");
        selec_art.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shoppaymentorderbuy-34_icon-icons.com_73865.png"))); // NOI18N
        getContentPane().add(selec_art, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marble-2398946_960_720.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void transparenciaBotones(){
    
        selec_gastronomia.setOpaque(false);
        selec_gastronomia.setContentAreaFilled(false);
        selec_gastronomia.setBorderPainted(true);
        
        selec_servicio.setOpaque(false);
        selec_servicio.setContentAreaFilled(false);
        selec_servicio.setBorderPainted(true);
        
        selec_decoracion.setOpaque(false);
        selec_decoracion.setContentAreaFilled(false);
        selec_decoracion.setBorderPainted(true);
        
        selec_lugar.setOpaque(false);
        selec_lugar.setContentAreaFilled(false);
        selec_lugar.setBorderPainted(true);
        
        selec_cliente.setOpaque(false);
        selec_cliente.setContentAreaFilled(false);
        selec_cliente.setBorderPainted(true);
        
        selec_art.setOpaque(false);
        selec_art.setContentAreaFilled(false);
        selec_art.setBorderPainted(true);
    }
    
    
    private void VOLVERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLVERMouseClicked
       proveedor ob18 = new proveedor();
       ob18.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_VOLVERMouseClicked

    private void selec_lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selec_lugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selec_lugarActionPerformed

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
        
        Modificar_archivo_prov ob22 = new Modificar_archivo_prov();
        Modificar_archivo_clien ob23 = new Modificar_archivo_clien();
        if(selec_cliente.isSelected()){
            ob23.setVisible(true);
            this.setVisible(false);
              ob23.cliente();
        }
        
        if(selec_gastronomia.isSelected()){
            ob22.setVisible(true);
            this.setVisible(false);
              ob22.gastronomia();
        }
         if(selec_decoracion.isSelected()){
            ob22.setVisible(true);
            this.setVisible(false);
              ob22.decoracion();
        }
        if(selec_servicio.isSelected()){
            ob22.setVisible(true);
            this.setVisible(false);
              ob22.servicios();
        }
        if(selec_lugar.isSelected()){
            ob22.setVisible(true);
            this.setVisible(false);
              ob22.lugar();
        }
         if(selec_art.isSelected()){
             Mod_art ob49 = new Mod_art();
            ob49.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_modificarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mod_selec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mod_selec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mod_selec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mod_selec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mod_selec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MODIFI;
    private javax.swing.JLabel TIT_USU;
    private javax.swing.JLabel TIT_USU1;
    private javax.swing.JButton VOLVER;
    private javax.swing.JLabel deseo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.ButtonGroup mod_prov;
    private javax.swing.JButton modificar;
    private javax.swing.JRadioButton selec_art;
    private javax.swing.JRadioButton selec_cliente;
    private javax.swing.JRadioButton selec_decoracion;
    private javax.swing.JRadioButton selec_gastronomia;
    private javax.swing.JRadioButton selec_lugar;
    private javax.swing.JRadioButton selec_servicio;
    // End of variables declaration//GEN-END:variables
}
