/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vel_on_time;

/**
 *
 * @author andre
 */
public class Modificar_archivo_clien extends javax.swing.JFrame {

    /**
     * Creates new form Modificar_archivo_clien
     */
    public Modificar_archivo_clien() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombre_cliente = new javax.swing.JLabel();
        MES = new javax.swing.JLabel();
        numero_invitados = new javax.swing.JLabel();
        id_cliente = new javax.swing.JLabel();
        presupuesto1 = new javax.swing.JLabel();
        ANO = new javax.swing.JLabel();
        DIA = new javax.swing.JLabel();
        rev_dia = new javax.swing.JTextField();
        rev_mes = new javax.swing.JTextField();
        rev_ano = new javax.swing.JTextField();
        rev_id = new javax.swing.JTextField();
        rev_nombre = new javax.swing.JTextField();
        rev_presupuesto = new javax.swing.JTextField();
        rev_invitados = new javax.swing.JTextField();
        selec_mod = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        deseo = new javax.swing.JLabel();
        REV_CLIEN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre_cliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        nombre_cliente.setText("Nombre cliente:");
        getContentPane().add(nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 119, 34));

        MES.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        MES.setText("MES:");
        getContentPane().add(MES, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, 34));

        numero_invitados.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        numero_invitados.setText("Numero de invitados:");
        getContentPane().add(numero_invitados, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 129, 34));

        id_cliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        id_cliente.setText("Id del cliente:");
        getContentPane().add(id_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 85, 34));

        presupuesto1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        presupuesto1.setText("Presupuesto:");
        getContentPane().add(presupuesto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 85, 34));

        ANO.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        ANO.setText("AÑO:");
        getContentPane().add(ANO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 39, 34));

        DIA.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        DIA.setText("DIA:");
        getContentPane().add(DIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 36, 34));
        getContentPane().add(rev_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 60, -1));
        getContentPane().add(rev_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 61, -1));
        getContentPane().add(rev_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 68, -1));

        rev_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rev_idActionPerformed(evt);
            }
        });
        getContentPane().add(rev_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 103, -1));
        getContentPane().add(rev_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 160, -1));
        getContentPane().add(rev_presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 103, -1));
        getContentPane().add(rev_invitados, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 130, -1));

        selec_mod.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        selec_mod.setText("Modificar");
        selec_mod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selec_mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selec_modMouseClicked(evt);
            }
        });
        getContentPane().add(selec_mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 100, 30));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO  A MODIFICAR CLIENTE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 50));

        volver.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        volver.setText("Volver");
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 70, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 560, 10));

        deseo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        deseo.setText("Ingrese el nombre del cliente que desea modificar: ");
        getContentPane().add(deseo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));
        getContentPane().add(REV_CLIEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marble-2398946_960_720.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rev_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rev_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rev_idActionPerformed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        Mod_selec ob24 = new Mod_selec();
        ob24.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverMouseClicked

    private void selec_modMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selec_modMouseClicked
        
    }//GEN-LAST:event_selec_modMouseClicked

    /**
     * @param args the command line arguments
     */
    void cliente(){
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_archivo_clien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_archivo_clien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_archivo_clien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_archivo_clien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_archivo_clien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ANO;
    private javax.swing.JLabel DIA;
    private javax.swing.JLabel MES;
    private javax.swing.JTextField REV_CLIEN;
    private javax.swing.JLabel deseo;
    private javax.swing.JLabel id_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nombre_cliente;
    private javax.swing.JLabel numero_invitados;
    private javax.swing.JLabel presupuesto1;
    private javax.swing.JTextField rev_ano;
    private javax.swing.JTextField rev_dia;
    private javax.swing.JTextField rev_id;
    private javax.swing.JTextField rev_invitados;
    private javax.swing.JTextField rev_mes;
    private javax.swing.JTextField rev_nombre;
    private javax.swing.JTextField rev_presupuesto;
    private javax.swing.JButton selec_mod;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
