/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vel_on_time;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 *
 * @author jose noel mantilla
 */
public class mostrar_cot extends javax.swing.JFrame {
private int randomico2;
private int prec2;
    /**
     * Creates new form mostrar_cot
     */
    public mostrar_cot() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cajita_grande = new javax.swing.JTextArea();
        volver = new javax.swing.JButton();
        imprimir_contrato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cajita_grande.setColumns(20);
        cajita_grande.setRows(5);
        jScrollPane1.setViewportView(cajita_grande);

        volver.setText("VOLVER");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });

        imprimir_contrato.setText("IMPRIMIR CONTRATO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(imprimir_contrato)
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver)
                    .addComponent(imprimir_contrato))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        todas_cot ob33 = new todas_cot();
        ob33.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverMouseClicked

    /**
     * @param args the command line arguments
     */
    
    void mostrar(int randomico, int precio){
       randomico2=randomico;
       prec2=precio;
       this.randomico2=randomico2;
       this.prec2= prec2;
        File archivo = null;  //apuntar al archivo almancenado DD
        FileReader contenido = null;  //acceder a todo el contenido del archivo
        BufferedReader linea = null; //accede linea a linea al contenido
        String a;
        int nmuI = 0;
        int valorTglobIn=0;
        String fid = null;
        String fnombre;
        String fni;
        String ffecha;
        String fvalorgastro;
        String fdeco;
        String fserv;
        String flug;
        String fvalortglob;
        String fartgast;
        String fartdeco;
        String fartserv;
        String fartlug;
            
        
        try {
            archivo = new File("src\\archivos\\Cotizaciones Realizadas.txt.txt");
            contenido = new FileReader(archivo);
            linea = new BufferedReader(contenido);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            
            String cadena = ""; //variable captura los datos del archivo
            while ((cadena = linea.readLine()) != null) { //recorre todo el archivo
             
                 String nmu[]= cadena.split(";");
                 nmuI= Integer.parseInt(nmu[1]);
                 String id[]= cadena.split(";");
                 fid= id[2];
                 String nombre[]= cadena.split(";");
                 String nI[]= cadena.split(";");
                 String fecha[]= cadena.split(";");
                 String valorGastro[]= cadena.split(";");}
                 String valortdaceo[]= cadena.split(";");
                 String valortserv[]= cadena.split(";");
                 String valortlug[]= cadena.split(";");
                 String valorTglob[]= cadena.split(";");
                 valorTglobIn= Integer.parseInt(valorTglob[10]);
                 String artGast[]= cadena.split(";");
                 String artDeco[]= cadena.split(";");
                 String artServ[]= cadena.split(";");
                 String artLug[]= cadena.split(";");
                 
                 if (randomico2==nmuI&& prec2==valorTglobIn){
                
                     cajita_grande.append("Numero de cotización: "+ nmuI);
                     cajita_grande.append("Numero de cotización: "+ fid );
                     
                
                     
                     
                 }
                
                
                 
                 
      

        } catch (IOException e) {
            System.out.print("Error consultando archivo");
        } finally {
            try {
                if (contenido != null) {
                    contenido.close();
                }
            } catch (IOException e1) {
                System.out.print("Error cerrando archivo");
            }
        }
    
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mostrar_cot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mostrar_cot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mostrar_cot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mostrar_cot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mostrar_cot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cajita_grande;
    private javax.swing.JButton imprimir_contrato;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
