/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vel_on_time;

/**
 *
 * @author jose noel mantilla
 */
public final class Quien extends javax.swing.JFrame {

    /**
     * Creates new form Quien
     */
    public Quien() {
        initComponents();
        transparenciaBotones();
        this.setLocationRelativeTo(null);
        ELEC_QUIEN.add(gerente);
        ELEC_QUIEN.add(empleado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ELEC_QUIEN = new javax.swing.ButtonGroup();
        bienvenido = new javax.swing.JLabel();
        bienvenido1 = new javax.swing.JLabel();
        gerente = new javax.swing.JRadioButton();
        empleado = new javax.swing.JRadioButton();
        enviar = new javax.swing.JButton();
        WEB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenido.setFont(new java.awt.Font("SFNS Display", 1, 18)); // NOI18N
        bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenido.setText("¿Quien eres?");
        getContentPane().add(bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 519, 32));

        bienvenido1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        bienvenido1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenido1.setText("BIENVENIDO A Vel On Time");
        bienvenido1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(bienvenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 519, 57));

        gerente.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.light"));
        gerente.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        gerente.setText("Gerente");
        gerente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gerente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user_12821.png"))); // NOI18N
        gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenteActionPerformed(evt);
            }
        });
        getContentPane().add(gerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 240, 70));

        empleado.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.light"));
        empleado.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        empleado.setText("Empleado");
        empleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/community_users_12977.png"))); // NOI18N
        getContentPane().add(empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 240, 70));

        enviar.setFont(new java.awt.Font("SFNS Display", 1, 18)); // NOI18N
        enviar.setText("Continuar");
        enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarMouseClicked(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 240, 48));

        WEB.setText("WEB");
        WEB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WEBMouseClicked(evt);
            }
        });
        getContentPane().add(WEB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 270, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marble-2398946_960_720.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void transparenciaBotones(){
    
        gerente.setOpaque(false);
        gerente.setContentAreaFilled(false);
        gerente.setBorderPainted(true);
        
        empleado.setOpaque(false);
        empleado.setContentAreaFilled(false);
        empleado.setBorderPainted(true);
        
    }
    
    
    
    private void enviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarMouseClicked
        
         Empleado ob3 = new Empleado(); 
         Gerente ob11 = new Gerente();
           
                    if(empleado.isSelected()){
                        ob3.setVisible(true);
                        this.setVisible(false);
                          
                    }
                    if(gerente.isSelected()){
                        ob11.setVisible(true);
                        this.setVisible(false);
                          
                    }
                    
    }//GEN-LAST:event_enviarMouseClicked

    private void gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerenteActionPerformed

    private void WEBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WEBMouseClicked
        Codigo_qr ob47 = new Codigo_qr();
        ob47.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_WEBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ELEC_QUIEN;
    private javax.swing.JButton WEB;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JLabel bienvenido1;
    private javax.swing.JRadioButton empleado;
    private javax.swing.JButton enviar;
    private javax.swing.JRadioButton gerente;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
