/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vel_on_time;

/**
 *
 * @author jose noel mantilla
 */
public final class Selec_evento extends javax.swing.JFrame {

    /**
     * Creates new form Evento
     */
    public Selec_evento() {
        initComponents();
        transparenciaBotones();
       this.setLocationRelativeTo(null);
       SELECALL.add(SELEC_15);
       SELECALL.add(SELEC_ANIVERSARIO);
       SELECALL.add(SELEC_BABY);
       SELECALL.add(SELEC_BAUTIZO);
       SELECALL.add(SELEC_BENI);
       SELECALL.add(SELEC_CENA);
       SELECALL.add(SELEC_COMUNION);
       SELECALL.add(SELEC_CONFIRMACION);
       SELECALL.add(SELEC_CUMPLE);
       SELECALL.add(SELEC_FAMILIAR);
       SELECALL.add(SELEC_FERIA);
       SELECALL.add(SELEC_GALA);
       SELECALL.add(SELEC_GRADUACION);
       SELECALL.add(SELEC_HALLOWEN);
       SELECALL.add(SELEC_INAGURACION);
       SELECALL.add(SELEC_MATRIMONIO);
       SELECALL.add(SELEC_NAVIDAD);
       SELECALL.add(SELEC_RETRAB);
       SELECALL.add(SELEC_SABBAT);
       SELECALL.add(SELEC_SOLTERO);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SELECALL = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        SELEC_ANIVERSARIO = new javax.swing.JRadioButton();
        SELEC_MATRIMONIO = new javax.swing.JRadioButton();
        SELEC_15 = new javax.swing.JRadioButton();
        SELEC_SOLTERO = new javax.swing.JRadioButton();
        SELEC_INAGURACION = new javax.swing.JRadioButton();
        SELEC_CONFIRMACION = new javax.swing.JRadioButton();
        SELEC_COMUNION = new javax.swing.JRadioButton();
        SELEC_BAUTIZO = new javax.swing.JRadioButton();
        SELEC_GALA = new javax.swing.JRadioButton();
        SELEC_RETRAB = new javax.swing.JRadioButton();
        SELEC_HALLOWEN = new javax.swing.JRadioButton();
        SELEC_SABBAT = new javax.swing.JRadioButton();
        SELEC_NAVIDAD = new javax.swing.JRadioButton();
        SELEC_CUMPLE = new javax.swing.JRadioButton();
        SELEC_CENA = new javax.swing.JRadioButton();
        SELEC_FAMILIAR = new javax.swing.JRadioButton();
        SELEC_GRADUACION = new javax.swing.JRadioButton();
        SELEC_FERIA = new javax.swing.JRadioButton();
        SELEC_BABY = new javax.swing.JRadioButton();
        SELEC_BENI = new javax.swing.JRadioButton();
        ENVIAR_SELEC = new javax.swing.JButton();
        VOLVER_SELEC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Menú de opciones");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 52));

        SELEC_ANIVERSARIO.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_ANIVERSARIO.setText("ANIVERSARIO");
        SELEC_ANIVERSARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELEC_ANIVERSARIOActionPerformed(evt);
            }
        });
        getContentPane().add(SELEC_ANIVERSARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        SELEC_MATRIMONIO.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_MATRIMONIO.setText("MATRIMONIO");
        getContentPane().add(SELEC_MATRIMONIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        SELEC_15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_15.setText("15 AÑOS");
        getContentPane().add(SELEC_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        SELEC_SOLTERO.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_SOLTERO.setText("DESPEDIDA DE SOLTERO");
        getContentPane().add(SELEC_SOLTERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        SELEC_INAGURACION.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_INAGURACION.setText("INAGURACION");
        SELEC_INAGURACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELEC_INAGURACIONActionPerformed(evt);
            }
        });
        getContentPane().add(SELEC_INAGURACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        SELEC_CONFIRMACION.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_CONFIRMACION.setText("CONFIRMACION");
        getContentPane().add(SELEC_CONFIRMACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        SELEC_COMUNION.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_COMUNION.setText("PRIMERA COMUNIÓN");
        getContentPane().add(SELEC_COMUNION, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        SELEC_BAUTIZO.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_BAUTIZO.setText("BAUTIZO");
        getContentPane().add(SELEC_BAUTIZO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        SELEC_GALA.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_GALA.setText("GALAS-COCTELES");
        getContentPane().add(SELEC_GALA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        SELEC_RETRAB.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_RETRAB.setText("REUNION DE TRABAJO");
        getContentPane().add(SELEC_RETRAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        SELEC_HALLOWEN.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_HALLOWEN.setText("FIESTAS DE HALLOWEN");
        getContentPane().add(SELEC_HALLOWEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        SELEC_SABBAT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_SABBAT.setText("SABBAT");
        getContentPane().add(SELEC_SABBAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        SELEC_NAVIDAD.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_NAVIDAD.setText("FIESTA NAVIDEÑA");
        getContentPane().add(SELEC_NAVIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        SELEC_CUMPLE.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_CUMPLE.setText("CUMPLEAÑOS");
        getContentPane().add(SELEC_CUMPLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        SELEC_CENA.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_CENA.setText("CENAS INTIMAS");
        getContentPane().add(SELEC_CENA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        SELEC_FAMILIAR.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_FAMILIAR.setText("REUNIONES FAMILIARES");
        getContentPane().add(SELEC_FAMILIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        SELEC_GRADUACION.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_GRADUACION.setText("GRADUACIONES");
        getContentPane().add(SELEC_GRADUACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        SELEC_FERIA.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_FERIA.setText("CONVENCION-FERIAS");
        getContentPane().add(SELEC_FERIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        SELEC_BABY.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_BABY.setText("BABY SHOWER");
        SELEC_BABY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELEC_BABYActionPerformed(evt);
            }
        });
        getContentPane().add(SELEC_BABY, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        SELEC_BENI.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SELEC_BENI.setText("BENEI MITZVÁ");
        getContentPane().add(SELEC_BENI, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        ENVIAR_SELEC.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        ENVIAR_SELEC.setText("Aceptar");
        ENVIAR_SELEC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ENVIAR_SELEC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENVIAR_SELECMouseClicked(evt);
            }
        });
        ENVIAR_SELEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENVIAR_SELECActionPerformed(evt);
            }
        });
        getContentPane().add(ENVIAR_SELEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 80, 30));

        VOLVER_SELEC.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        VOLVER_SELEC.setText("Volver");
        VOLVER_SELEC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VOLVER_SELEC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLVER_SELECMouseClicked(evt);
            }
        });
        getContentPane().add(VOLVER_SELEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marble-2398946_960_720.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void transparenciaBotones(){
    
        SELEC_ANIVERSARIO.setOpaque(false);
        SELEC_ANIVERSARIO.setContentAreaFilled(false);
        SELEC_ANIVERSARIO.setBorderPainted(false);
        
        SELEC_MATRIMONIO.setOpaque(false);
        SELEC_MATRIMONIO.setContentAreaFilled(false);
        SELEC_MATRIMONIO.setBorderPainted(false);
        
        SELEC_15.setOpaque(false);
        SELEC_15.setContentAreaFilled(false);
        SELEC_15.setBorderPainted(false);
        
        SELEC_SOLTERO.setOpaque(false);
        SELEC_SOLTERO.setContentAreaFilled(false);
        SELEC_SOLTERO.setBorderPainted(false);
        
        SELEC_INAGURACION.setOpaque(false);
        SELEC_INAGURACION.setContentAreaFilled(false);
        SELEC_INAGURACION.setBorderPainted(false);
        
        SELEC_CONFIRMACION.setOpaque(false);
        SELEC_CONFIRMACION.setContentAreaFilled(false);
        SELEC_CONFIRMACION.setBorderPainted(false);
        
        SELEC_COMUNION.setOpaque(false);
        SELEC_COMUNION.setContentAreaFilled(false);
        SELEC_COMUNION.setBorderPainted(false);
        
        SELEC_BAUTIZO.setOpaque(false);
        SELEC_BAUTIZO.setContentAreaFilled(false);
        SELEC_BAUTIZO.setBorderPainted(false);
        
        SELEC_GALA.setOpaque(false);
        SELEC_GALA.setContentAreaFilled(false);
        SELEC_GALA.setBorderPainted(false);
        
        SELEC_RETRAB.setOpaque(false);
        SELEC_RETRAB.setContentAreaFilled(false);
        SELEC_RETRAB.setBorderPainted(false);
        
        SELEC_CUMPLE.setOpaque(false);
        SELEC_CUMPLE.setContentAreaFilled(false);
        SELEC_CUMPLE.setBorderPainted(false);
        
        SELEC_CENA.setOpaque(false);
        SELEC_CENA.setContentAreaFilled(false);
        SELEC_CENA.setBorderPainted(false);
        
        SELEC_FAMILIAR.setOpaque(false);
        SELEC_FAMILIAR.setContentAreaFilled(false);
        SELEC_FAMILIAR.setBorderPainted(false);
        
        SELEC_GRADUACION.setOpaque(false);
        SELEC_GRADUACION.setContentAreaFilled(false);
        SELEC_GRADUACION.setBorderPainted(false);
        
        SELEC_FERIA.setOpaque(false);
        SELEC_FERIA.setContentAreaFilled(false);
        SELEC_FERIA.setBorderPainted(false);
        
        SELEC_BABY.setOpaque(false);
        SELEC_BABY.setContentAreaFilled(false);
        SELEC_BABY.setBorderPainted(false);
        
        SELEC_BENI.setOpaque(false);
        SELEC_BENI.setContentAreaFilled(false);
        SELEC_BENI.setBorderPainted(false);
        
        SELEC_HALLOWEN.setOpaque(false);
        SELEC_HALLOWEN.setContentAreaFilled(false);
        SELEC_HALLOWEN.setBorderPainted(false);
        
        SELEC_SABBAT.setOpaque(false);
        SELEC_SABBAT.setContentAreaFilled(false);
        SELEC_SABBAT.setBorderPainted(false);
        
        SELEC_NAVIDAD.setOpaque(false);
        SELEC_NAVIDAD.setContentAreaFilled(false);
        SELEC_NAVIDAD.setBorderPainted(false);
    }
    
    
    
    
    private void SELEC_ANIVERSARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELEC_ANIVERSARIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SELEC_ANIVERSARIOActionPerformed

    private void SELEC_INAGURACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELEC_INAGURACIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SELEC_INAGURACIONActionPerformed

    private void SELEC_BABYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELEC_BABYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SELEC_BABYActionPerformed

    private void ENVIAR_SELECMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENVIAR_SELECMouseClicked
           Evento ob2 = new Evento(); 
           
                    if(SELEC_ANIVERSARIO.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.aniversario();
                    }
                    if(SELEC_MATRIMONIO.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                        ob2.matrimonio();
                    }
                    if(SELEC_15.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.quince();
                       }
                    if(SELEC_SOLTERO.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.soltero();
                       }
                    if(SELEC_INAGURACION.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.inaguracion();
                       }
                    if(SELEC_CONFIRMACION.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.confirmacion();
                       }
                    if(SELEC_BAUTIZO.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.bautizo();
                       }
                    if(SELEC_COMUNION.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.comunion();
                       }
                    if(SELEC_BAUTIZO.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.bautizo();
                       }
                    if(SELEC_GALA.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.galas();
                       }
                    if(SELEC_RETRAB.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.reuniones();
                       }
                    if(SELEC_CUMPLE.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.cumple();
                       }
                    if(SELEC_FAMILIAR.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.reuFam();
                       }
                    if(SELEC_GRADUACION.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.graduacion();
                       }
                    if(SELEC_FERIA.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.convenciones();
                    }
                    if(SELEC_BABY.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.baby();
                    }
                    if(SELEC_BENI.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.benei();
                    }
                    if(SELEC_HALLOWEN.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.halloween();
                    }
                    if(SELEC_SABBAT.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.sabbat();
                    }
                    if(SELEC_NAVIDAD.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.navidad();
                    }
                     if(SELEC_CENA.isSelected()){
                        ob2.setVisible(true);
                        this.setVisible(false);
                          ob2.cenas();
                    }
                    
    }//GEN-LAST:event_ENVIAR_SELECMouseClicked

    private void VOLVER_SELECMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLVER_SELECMouseClicked
                       Empleado ob8 = new Empleado();
                       ob8.setVisible(true);
                       this.setVisible(false);
    }//GEN-LAST:event_VOLVER_SELECMouseClicked

    private void ENVIAR_SELECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENVIAR_SELECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ENVIAR_SELECActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selec_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selec_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selec_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selec_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selec_evento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ENVIAR_SELEC;
    private javax.swing.ButtonGroup SELECALL;
    private javax.swing.JRadioButton SELEC_15;
    private javax.swing.JRadioButton SELEC_ANIVERSARIO;
    private javax.swing.JRadioButton SELEC_BABY;
    private javax.swing.JRadioButton SELEC_BAUTIZO;
    private javax.swing.JRadioButton SELEC_BENI;
    private javax.swing.JRadioButton SELEC_CENA;
    private javax.swing.JRadioButton SELEC_COMUNION;
    private javax.swing.JRadioButton SELEC_CONFIRMACION;
    private javax.swing.JRadioButton SELEC_CUMPLE;
    private javax.swing.JRadioButton SELEC_FAMILIAR;
    private javax.swing.JRadioButton SELEC_FERIA;
    private javax.swing.JRadioButton SELEC_GALA;
    private javax.swing.JRadioButton SELEC_GRADUACION;
    private javax.swing.JRadioButton SELEC_HALLOWEN;
    private javax.swing.JRadioButton SELEC_INAGURACION;
    private javax.swing.JRadioButton SELEC_MATRIMONIO;
    private javax.swing.JRadioButton SELEC_NAVIDAD;
    private javax.swing.JRadioButton SELEC_RETRAB;
    private javax.swing.JRadioButton SELEC_SABBAT;
    private javax.swing.JRadioButton SELEC_SOLTERO;
    private javax.swing.JButton VOLVER_SELEC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
